config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   password: 'users/passwords',
  #   registrations: 'users/registrations'
  # }
  devise_scope :user do
    post 'users', to: 'users/registrations#create'
  end
  root to: 'tops#index'
  get 'users/history'
  get 'users/favorite'
  get 'tops/show'
  devise_for :users
  get 'projects/search'
  get 'free_traders/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :rooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  resources :projects, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :project_favorites, only: [:create, :destroy]
  end

  resources :free_traders, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :trader_favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :profile_image

  has_many :projects, dependent: :destroy
  has_many :free_trader, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :messages
  has_many :project_favorites, dependent: :destroy
  has_many :trader_favorites, dependent: :destroy

  enum residence: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  # enum skill: {
  #   LGS:1,クロス:2,左官:3,ガラス:4,貼床:5,荷揚:6,雑工:7,電気:8,塗装:9,大工:10,シール:11,鳶:12,置床:13,防災:14,サイン:15,サッシ:16,建具:17,デザイン:18,設計:19,施工管理:20
  # }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def create
    build_resource(sign_up_params)
        session[:room] = {}
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)

        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end


  def after_sign_up_path_for(resource)
    edit_user_path(current_user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    unless @user.skill == nil
      @user_skills = @user.skill.split(", ")
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path
    end
  end

  def create
  end

  def update
    @user =User.find(params[:id])
    unless user_params[:skill] == nil
    a = user_params[:skill].join(", ")
    @user.update(email: user_params[:email], name: user_params[:name], skill: a, kind_id: user_params[:kind_id],
                 residence: user_params[:residence], profile_image:user_params[:profile_image], pr:user_params[:pr], experience: user_params[:experience],
                 top_image_id: user_params[:top_image_id], mission: user_params[:mission],service: user_params[:service], establishment: user_params[:establishment],
                 employee: user_params[:employee], average_age: user_params[:average_age], catchphrase: user_params[:catchphrase], detail_residence: user_params[:detail_residence])
    redirect_to user_path(@user.id)
  else
    @user.update(email: user_params[:email], name: user_params[:name], kind_id: user_params[:kind_id],
                 residence: user_params[:residence], profile_image:user_params[:profile_image], pr:user_params[:pr], experience: user_params[:experience],
                 top_image_id: user_params[:top_image_id], mission: user_params[:mission],service: user_params[:service], establishment: user_params[:establishment],
                 employee: user_params[:employee], average_age: user_params[:average_age], catchphrase: user_params[:catchphrase], detail_residence: user_params[:detail_residence])
    redirect_to user_path(@user.id)
  end
  end

  def history
    @user = current_user
    @projects = Project.where(user_id: @user)
    @free_traders = FreeTrader.where(user_id: @user)
  end

  def favorite
    @user = current_user
    project = ProjectFavorite.where(user_id: @user)
    a = project.pluck(:project_id)
    @projects = Project.where(id: a)
    trader = TraderFavorite.where(user_id: @user)
    b = trader.pluck(:free_trader_id)
    @free_traders = FreeTrader.where(id:b)
  end


  private

  def user_params
      params.require(:user).permit(:name,:kind_id,:residence,:profile_image,:pr,:experience, :email, :top_image_id, :mission, :service, :establishment, :employee, :average_age, :catchphrase, :detail_residence, skill: [])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<body>
		<div class="user-main-content">
			<%=form_for(@user) do |f| %>
				<div class="user-edit-top">
					<div class="user-edit-title"><span>会社情報</span></div>
						<div class="user-edit-image">
							<%= attachment_image_tag @user, :profile_image, :fill, 120, 120, format: 'jpeg', class: "img-circle", fallback: "user1.png", :size => "120x120" %>
							<label for="files">
								<div class="btn btn-image-edit">プロフィール写真選択</div>
								<%=f.attachment_field :profile_image, plaeholder:"プロフィール画像",id: "files", class: "user-edit-form" %>
							</label>
						</div>
						<div class="many-fields">
							<div class="field">
								<%= f.label :会社名 %><br />
								<%= f.text_field :name, autofocus: true, class: "user-edit-name" %>
							</div>
							<div class="field">
								<%= f.label :メールアドレス %><br />
								<%= f.email_field :email, class: "user-edit-email" %>
							</div>
							<div class="field">
								<%= f.label :会社住所 %><br />
								<%= f.select :residence, User.residences.keys, {prompt: '選択してください'}, class: 'project-edit-location btn btn-edit-residence' %>
								<br>
								<br>
								<%= f.text_field :detail_residence, autofocus: true, class: "project-edit-title" %>
							</div>
							<div class="field">
								<%= f.label :設立年 %><br />
								<%= f.text_field :establishment, autofocus: true, class: "user-edit-name" %>
							</div>
							<div class="field">
								<%= f.label :従業員数 %><br />
								<%= f.text_field :employee, autofocus: true, class: "user-edit-name" %>
							</div>
							<div class="field">
								<%= f.label :平均年齢 %><br />
								<%= f.text_field :average_age, autofocus: true, class: "user-edit-name" %>
							</div>
						</div>
				</div>
				<div class="user-pr clearfix">
					<div class="user-pr-title">
						<div class="pr-description-title">
							会社概要
						</div>
						<br>
						<p class="pr-description-text">会社としての方針をセールスポイントとして伝えましょう。</p>
					</div>
					<div class="user-pr-text">
						<%= f.text_area :mission, rows:'11', class: "form-control pr" %>
					</div>
				</div>
				<div class="user-pr clearfix">
					<div class="user-pr-title">
						<div class="pr-description-title">
							事業内容
						</div>
						<br>
						<p class="pr-description-text">会社としてどのようなサービスを提供しているのか明確に記入しましょう。</p>
					</div>
					<div class="user-pr-text">
						<%= f.text_area :service, rows:'11', class: "form-control pr ",placeholder: "" %>
					</div>
				</div>
				<div class="user-pr clearfix">
					<div class="user-pr-title">
						<div class="pr-description-title">
							実績・経験
						</div>
						<br>
						<p class="pr-description-text">これまでの職場での業務内容や、果たした役割などを明確に記入しましょう。</p>
					</div>
					<div class="user-pr-text">
						<%= f.text_area :experience, rows:'11', class: "form-control pr ",placeholder: "" %>
					</div>
				</div>
				<div class="user-pr clearfix">
					<div class="user-pr-title">
						<div class="pr-description-title">
							対応工事
						</div>
						<br>
						<p class="pr-description-text">自分が持っているスキルを記入しましょう。<br>マッチングが高まります。</p>
					</div>
					<div class="user-pr-text clearfix">
						<div class="user-pr-skill-1">
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="LGS" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;LGS&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="クロス" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;クロス&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="左官" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;左官&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="ガラス" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;ガラス&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="貼床" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;貼床&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
						</div>
						<div class="user-pr-skill-2">
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="荷揚" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;荷揚&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="雜工" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;雑工&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="電気" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;電気&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="塗装" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;塗装&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill ">
								<input class="skill" type="checkbox" value="大工" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;大工&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
						</div>
						<div class="user-pr-skill-3">
							<label class="btn btn-skill">
								<input  class="skill" type="checkbox" value="シール" name="user[skill][]"  >&nbsp;&nbsp;&nbsp;&nbsp;シール&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="鳶" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;鳶&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="置床" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;置床&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="防災" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;防災&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="サイン" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;サイン&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
						</div>
						<div class="user-pr-skill-4">
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="サッシ" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;サッシ&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="建具" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;建具&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="デザイン" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;デザイン&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="設計" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;設計&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
							<label class="btn btn-skill">
								<input  class="skill"type="checkbox" value="施工管理" name="user[skill][]" >&nbsp;&nbsp;&nbsp;&nbsp;施工管理&nbsp;&nbsp;&nbsp;&nbsp;
							</label>
						</div>
					</div>
				</div>
				<div class="user-profile-complete">
					<%= f.submit "新規登録完了", class: "btn btn-complete" %>
				</div>
		</div>
	<% end %>
</body>

app/views/users/favorite.html.erb
<div class="history-content">
	<div class="history-title">
		お気に入り案件情報
	</div>
	<div class="history-project">
		<% if @projects.present? %>
			<% @projects.each do |project| %>
				<%= link_to project_path(project.id) do %>
					<div class="history-box">
						<div class="btn btn-title"><%= project.genre %></div>
						<div class="history-box-text"><%= project.project_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="history-box-name"><%= project.user.name %></div>
								<div class="history-box-info">¥<%= project.fee %>&nbsp;&nbsp;&nbsp;&nbsp;<%= project.location %></div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag project.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% else %>
			<div class="history-nil">
				<div class="historry-nill-text">お気に入りはありません</div>
			</div>
		<% end %>
	</div>
	<div class="history-title">
		お気に入り空き情報
	</div>
	<div class="history-project">
		<% if @free_traders.present? %>
			<% @free_traders.each do |trader| %>
				<%= link_to free_trader_path(trader.id) do %>
					<div class="history-box">
						<div class="btn btn-title"><%= trader.trader_genre %></div>
						<div class="history-box-text"><%= trader.trader_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="history-box-name"><%= trader.user.name %></div>
								<div class="history-box-info"><%= trader.user.residence %></div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag trader.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% else %>
			<div class="history-nil">
				<div class="historry-nill-text">お気に入りはありません</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/history.html.erb
<div class="history-content">
	<div class="history-title">
		案件情報投稿履歴
	</div>
	<div class="history-project">
		<% unless @projects == nil %>
			<% @projects.each do |project| %>
				<%= link_to project_path(project.id) do %>
					<div class="history-box">
						<div class="btn btn-title"><%= project.genre %></div>
						<div class="history-box-text"><%= project.project_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="history-box-name"><%= project.user.name %></div>
								<div class="history-box-info">¥<%= project.fee %>&nbsp;&nbsp;&nbsp;&nbsp;<%= project.location %></div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag project.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% else %>
			<div class="history-nil">
				<div class="historry-nill-text">まだ投稿はありません</div>
			</div>
		<% end %>
	</div>
	<div class="history-title">
		空き情報投稿履歴
	</div>
	<div class="history-project">
		<% unless @free_traders == nil %>
			<% @free_traders.each do |trader| %>
				<%= link_to free_trader_path(trader.id) do %>
					<div class="history-box">
						<div class="btn btn-title"><%= trader.trader_genre %></div>
						<div class="history-box-text"><%= trader.trader_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="history-box-name"><%= trader.user.name %></div>
								<div class="history-box-info"><%= trader.user.residence %></div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag trader.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% else %>
			<div class="history-nil">
				<div class="historry-nill-text">まだ投稿はありません</div>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<body>
    <div class="user-main-content">
      <div class="company-profile-top">
        <div class="user-profile-image">
          <%= attachment_image_tag @user, :profile_image, :fill, 120, 120, format: 'jpeg', fallback: "user1.png", :size => "110x110" %>
        </div>
        <div class="user-profile-name">
          <strong><%= @user.name %></strong>
        </div>
        <div class="user-profile-residence">
          <%= @user.residence %>
        </div>
        <% if user_signed_in? %>
          <% if @user == current_user %>
            <div class="user-profile-edit">
              <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-edit" %>
            </div>
          <% else %>
            <%= link_to rooms_path(id: @user.id),method: :post do %>
              <div class="user-profile-edit">
                <p class="btn btn-edit">メッセージを送る</p>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="project-info-content clearfix">
        <div class="project-info-main">
          <div class="project-info-title">会社概要</div>
          <p class="english-info-title">Mission</p>
          <% if @user.mission == nil || @user.mission == "" %>
            <div class="company-pr-text">
              <div class="nil-profile-pr-text">ミッションが設定されていません</div>
            </div>
              <br>
              <br>
          <% else %>
          <div class="project-info-text"><%= simple_format(@user.mission) %> </div>
          <% end %>
          <div class="project-info-title">事業内容</div>
          <p class="english-info-title">Service</p>
            <% if @user.service == nil || @user.service == "" %>
                <div class="company-pr-text">
                  <div class="nil-profile-pr-text">ミッションが設定されていません</div>
                </div>
            <% else %>
              <div class="project-info-text"><%= simple_format(@user.service) %> </div>
            <% end %>
          <div class="project-info-title">実績</div>
          <p class="english-info-title">Performance</p>
            <% if @user.experience == nil || @user.experience == "" %>
                <div class="company-pr-text">
                  <div class="nil-profile-pr-text">実績が設定されていません</div>
                </div>
                <br>
                <br>
            <% else %>
              <div class="project-info-text"><%= simple_format(@user.experience) %> </div>
            <% end %>
          </div>
        <div class="company-info-side">
          <div class="side-company">
            <div class="side-company-name">
              <%= @user.name %>
                <p><%= @user.residence %><%= @user.detail_residence %></p>
              </div>
            <table class="company-side-info">
              <tbody>
                <tr>
                  <td>設立年</td>
                  <td><%= @user.establishment %></td>
                </tr>
                <tr>
                  <td>従業員数</td>
                  <td><%= @user.employee %></td>
                </tr>
                <tr>
                  <td>平均年齢</td>
                  <td><%= @user.average_age %></td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="side-skill">
            <div class="side-company-skill"">対応工事</div>
            <% unless @user.skill == nil %>
                <% @user_skills.each do |skill| %>
                  <li class="btn btn-side-skill"><%= skill %></li>
                <% end %>
            <% end%>
          </div>
        </div>
      </div>
    </div>
</body>