config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   password: 'users/passwords',
  #   registrations: 'users/registrations'
  # }
  devise_scope :user do
    post 'users', to: 'users/registrations#create'
  end
  root to: 'tops#index'
  get 'users/history'
  get 'users/favorite'
  get 'tops/show'
  devise_for :users
  get 'projects/search'
  get 'free_traders/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :rooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  resources :projects, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :project_favorites, only: [:create, :destroy]
  end

  resources :free_traders, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :trader_favorites, only: [:create, :destroy]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :project_title, presence: true
  validates :genre, presence: true
  validates :location, presence: true
  validates :first_term, presence: true
  validates :second_term, presence: true


  attachment :project_image

  belongs_to :user

  has_many :project_favorites, dependent: :destroy

    enum location: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

    enum genre: {
    LGS:1,クロス:2,左官:3,ガラス:4,貼床:5,荷揚:6,雑工:7,電気:8,塗装:9,大工:10,シール:11,鳶:12,置床:13,防災:14,サイン:15,サッシ:16,建具:17,デザイン:18,設計:19,施工管理:20
  }

  def favorited_by?(user)
    project_favorites.where(user_id: user.id).exists?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.page(params[:page]).per(10)
    expired = Project.where("first_term < ?", Date.today)
    expired.each do |expired|
      expired.destroy
    end
  end

  def show
    @project = Project.find(params[:id])
    unless @project.user.skill == nil
      @user_skills = @project.user.skill.split(", ")
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project.id)
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
    if @project.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    project = Project.find(params[:id])
    project.update(project_params)
    redirect_to project_path(project.id)
  end

  def destroy
    project = Project.find(params[:id])
    project.destroy
    redirect_to user_path(current_user.id)
  end

  def search
    expired = Project.where("first_term < ?", Date.today)
    expired.each do |expired|
      expired.destroy
    end
    @projects = Project.where("project_title like '%" + params[:search] +
                              "%' and genre like '%" + Project.genres[params[:genre]].to_s + "%' and location like '%" + Project.locations[params[:location]].to_s + "%'")
  end

  private
    def project_params
      params.require(:project).permit(:genre,:location,:fee,:time,:project_content,:project_title,:required_skill,:welcome_skill,:project_image_id,:detail_location,:first_term, :second_term)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<body>
		<div class="project-main-content">
			<%=form_for(@project) do |f| %>
				<div class="project-top">
					<div class="project-topic"><span>案件情報編集</span></div>
						<div class="many-fields">
							<div class="field">
								<%= f.label :案件情報見出し %><br />
								<%= f.text_field :project_title, autofocus: true, class: "project-edit-title" %>
							</div>
							<div class="field">
								<%= f.label :給与 %><br />
								<%= f.text_field :fee,  class: "project-edit-fee" %><strong>円</strong>
							</div>
							<div class="field">
								<%= f.label :現場住所 %><br />
								<%= f.select :location, Project.locations.keys, {prompt: '選択してください'}, class: 'project-edit-location btn btn-edit-residence' %><br>
								<br>
								<%= f.text_field :detail_location, autofocus: true, class: "project-edit-title" %>
							</div>
							<div class="field">
								<%= f.label :職種 %><br />
								<%= f.select :genre, Project.genres.keys, {prompt: '選択してください'}, class: 'project-edit-location btn btn-edit-residence' %>
							</div>
							<div class="field">
								<%= f.label :業務時間 %><br />
								<%= f.text_field :time,  class: "project-edit-fee" %>
							</div>
							<div class="field">
								<%= f.label :工事期間 %><br />
								<%= f.date_field :first_term,  class: "project-edit-date" %><strong>〜</strong><%= f.date_field :second_term,  class: "project-edit-date" %>
							</div>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								業務内容
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :project_content, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								必須スキル
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :required_skill, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								歓迎スキル
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :welcome_skill, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-profile-complete">
                		<%= f.submit "案件登録完了", class: "btn btn-complete" %>
              		</div>
			<% end %>
		</div>
</body>

app/views/projects/index.html.erb
<div class="project-serch">
	<div class="search">
		<%= form_tag projects_search_path, method: :get do %>
		<div class= "search-area">
			<%= label_tag :キーワード %><br/>
			<%= text_field_tag :search, params[:search], class: "search_box" %>
		</div>
		<div class= "search-area">
			<%= label_tag :職種 %><br/>
			<%= select_tag 'genre', options_for_select(Project.genres.keys), :include_blank => true, class: "genre_box" %>
		</div>
		<div class= "search-area">
			<%= label_tag :現場地域 %><br/>
			<%= select_tag 'location', options_for_select(Project.locations.keys), :include_blank => true, class: "location_box" %>
		</div>
		<%= submit_tag "検索", class: "btn btn-search" %>
		<% end %>
	</div>
</div>
<div class="project-content clearfix">
	<div class="project-main">
		<p>案件一覧</p>
		<% @projects.each do |project| %>
				<div class="project-box">
					<div class="project-box-top clearfix">
						<div class="btn btn-title"><%= project.genre %></div>
						<% a = project.first_term %>
						<% b = (a - Date.today).to_i %>
						<% if b <= 10 %>
						<div class="btn btn-deadline"> あと<%= b %>日</div>
						<% else %>
						<div class="btn btn-title"> あと<%= b %>日</div>
						<% end %>
						<% if user_signed_in? %>
							<div class="project-box-favorite"><%= render 'project_favorites/favorite', project: project %>
							</div>
						<% end %>
					</div>
					<%= link_to project_path(project.id) do %>
						<div class="project-box-text"><%= project.project_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="project-box-name"><%= project.user.name %>
								</div>
								<div class="project-box-info">¥<%= project.fee %>&nbsp;&nbsp;&nbsp;&nbsp;<%= project.location %>
								</div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag project.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
				<% end %>
			</div>
		<% end %>
		<%= paginate @projects %>
	</div>
	<div class="project-side">
		<div class="side-search-title">おすすめ検索ワード</div>
		<p>現場エリア</p>
		<a href="/projects/search?utf8=✓&search=&genre=&location=東京都"><li class="btn btn-default">東京</li></a>
		<a href="/projects/search?utf8=✓&search=&genre=&location=神奈川県"><li class="btn btn-default">神奈川</li></a>
		<a href="/projects/search?utf8=✓&search=&genre=&location=大阪府"><li class="btn btn-default">大阪</li></a>
		<a href="/projects/search?utf8=✓&search=&genre=&location=埼玉県"><li class="btn btn-default">埼玉</li></a>
		<a href="/projects/search?utf8=✓&search=&genre=&location=福岡県"><li class="btn btn-default">福岡</li></a>
		<a href="/projects/search?utf8=✓&search=&genre=&location=北海道"><li class="btn btn-default">北海道</li></a>
		<p>職種</p>
		<a href= "/projects/search?utf8=✓&search=&genre=大工&location="><li class="btn btn-default">大工</li></a>
		<a href= "/projects/search?utf8=✓&search=&genre=左官&location="><li class="btn btn-default">左官</li></a>
		<a href= "/projects/search?utf8=✓&search=&genre=左官&location="><li class="btn btn-default">塗装</li></a>
		<a href= "/projects/search?utf8=✓&search=&genre=施工管理&location="><li class="btn btn-default">施工管理</li></a>
		<a href= "/projects/search?utf8=✓&search=&genre=設計&location="><li class="btn btn-default">設計</li></a>
		<a href= "/projects/search?utf8=✓&search=&genre=デザイン&location="><li class="btn btn-default">デザイナー</li></a>
	</div>
</div>

app/views/projects/new.html.erb
<body>
		<div class="project-main-content">
			<%=form_for(@project) do |f| %>
				<div class="project-top">
					<div class="project-topic"><span>新規案件依頼</span></div>
						<div class="many-fields">
							<div class="field">
								<%= f.label :案件情報見出し %><br />
								<%= f.text_field :project_title, autofocus: true, class: "project-edit-title" %>
							</div>
							<div class="field">
								<%= f.label :給与 %><br />
								<%= f.text_field :fee,  class: "project-edit-fee" %><strong>円</strong>
							</div>
							<div class="field">
								<%= f.label :現場住所 %><br />
								<%= f.select :location, Project.locations.keys, {prompt: '選択してください'}, class: 'project-edit-location btn btn-edit-residence' %><br>
								<br>
								<%= f.text_field :detail_location, autofocus: true, class: "project-edit-title" %>
							</div>
							<div class="field">
								<%= f.label :職種 %><br />
								<%= f.select :genre, Project.genres.keys, {prompt: '選択してください'}, class: 'project-edit-location btn btn-edit-residence' %>
							</div>
							<div class="field">
								<%= f.label :工期 %><br />
								<%= f.date_field :first_term,  class: "project-edit-date" %><strong>〜</strong><%= f.date_field :second_term,  class: "project-edit-date" %>
							</div>
							<div class="field">
								<%= f.label :業務時間 %><br />
								<%= f.text_field :time,  class: "project-edit-fee" %>
							</div>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								業務内容
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :project_content, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								必須スキル
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :required_skill, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-pr clearfix">
						<div class="user-pr-title">
							<div class="pr-description-title">
								歓迎スキル
							</div>
							<br>
							<p class="pr-description-text">現場での業務内容を明確に記載しよう<br>明確に記載することでトラブルを防げます。</p>
						</div>
						<div class="user-pr-text">
							<%= f.text_area :welcome_skill, rows:'11', class: "form-control pr" %>
						</div>
					</div>
					<div class="user-profile-complete">
                		<%= f.submit "案件登録完了", class: "btn btn-complete" %>
              		</div>
			<% end %>
		</div>
</body>

app/views/projects/search.html.erb
<div class="project-serch">
	<div class="search">
		<%= form_tag projects_search_path, method: :get do %>
		<div class= "search-area">
			<%= label_tag :キーワード %><br/>
			<%= text_field_tag :search, params[:search], class: "search_box" %>
		</div>
		<div class= "search-area">
			<%= label_tag :職種 %><br/>
			<%= select_tag 'genre', options_for_select(Project.genres.keys), :include_blank => true, class: "genre_box" %>
		</div>
		<div class= "search-area">
			<%= label_tag :現場地域 %><br/>
			<%= select_tag 'location', options_for_select(Project.locations.keys), :include_blank => true, class: "location_box" %>
		</div>
		<%= submit_tag "検索", class: "btn btn-search" %>
		<% end %>
	</div>
</div>
<div class="project-content clearfix">
	<div class="project-main clearfix">
		<% if @projects.present? %>
			<p>案件情報検索結果</p>
			<% @projects.each do |project| %>
				<div class="project-box">
					<div class="project-box-top clearfix">
						<div class="btn btn-title"><%= project.genre %></div>
						<% a = project.first_term %>
						<% b = (a - Date.today).to_i %>
						<% if b <= 10 %>
							<div class="btn btn-deadline"> あと<%= b %>日</div>
						<% else %>
							<div class="btn btn-title"> あと<%= b %>日</div>
						<% end %>
						<div class="project-box-favorite"><%= render 'project_favorites/favorite', project: project %></div>
					</div>
					<%= link_to project_path(project.id) do %>
					<div class="project-box-text"><%= project.project_title %></div>
						<div class="box-info clearfix">
							<div class="box-info-left">
								<div class="project-box-name"><%= project.user.name %></div>
								<div class="project-box-info">¥<%= project.fee %>&nbsp;&nbsp;&nbsp;&nbsp;<%= project.location %></div>
							</div>
							<div class="box-info-right">
								<div class="project-box-image"><%= attachment_image_tag project.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
							</div>
						</div>
					<% end %>
				</div>
			<% end %>
		<% else %>
			<div class="search-nil">
				<div class="search-nill-text"><% if params[:search].present? %>「<%= params[:search] %>」</br><% end %>
																			<% if params[:genre].present? %>「<%= params[:genre] %>」<% end %>
																			<% if params[:location].present? %>「<%= params[:location] %>」<% end %><br/>該当結果なし
				</div>
			</div>
		<% end %>
	</div>
		<div class="project-side">
			<div class="side-search-title">おすすめ検索ワード</div>
			<p>現場エリア</p>
			<a href="/projects/search?utf8=✓&search=&genre=&location=東京都"><li class="btn btn-default">東京</li></a>
			<a href="/projects/search?utf8=✓&search=&genre=&location=神奈川県"><li class="btn btn-default">神奈川</li></a>
			<a href="/projects/search?utf8=✓&search=&genre=&location=大阪府"><li class="btn btn-default">大阪</li></a>
			<a href="/projects/search?utf8=✓&search=&genre=&location=埼玉県"><li class="btn btn-default">埼玉</li></a>
			<a href="/projects/search?utf8=✓&search=&genre=&location=福岡県"><li class="btn btn-default">福岡</li></a>
			<a href="/projects/search?utf8=✓&search=&genre=&location=北海道"><li class="btn btn-default">北海道</li></a>
			<p>職種</p>
			<a href= "/projects/search?utf8=✓&search=&genre=大工&location="><li class="btn btn-default">大工</li></a>
			<a href= "/projects/search?utf8=✓&search=&genre=左官&location="><li class="btn btn-default">左官</li></a>
			<a href= "/projects/search?utf8=✓&search=&genre=塗装&location="><li class="btn btn-default">塗装</li></a>
			<a href= "/projects/search?utf8=✓&search=&genre=施工管理&location="><li class="btn btn-default">施工管理</li></a>
			<a href= "/projects/search?utf8=✓&search=&genre=設計&location="><li class="btn btn-default">設計</li></a>
			<a href= "/projects/search?utf8=✓&search=&genre=デザイン&location="><li class="btn btn-default">デザイナー</li></a>
		</div>
</div>

app/views/projects/show.html.erb
<div class="project-info">
	<div class="project-info-top">
		<div class="client-image">
			<%= attachment_image_tag @project.user, :profile_image, :fill, 120, 120, format: 'jpeg', fallback: "user1.png", :size => "100x100" %>
		</div>
		<div class="btn btn-genre"><%= @project.genre %></div>
		<% a = @project.first_term %>
		<% b = (a - Date.today).to_i %>
		<% if b <= 10 %>
		<div class="btn btn-deadline-show"> あと<%= b %>日</div>
		<% else %>
		<div class="btn btn-genre"> あと<%= b %>日</div>
		<% end %>
		<div class="project-title"><strong><%= @project.project_title %></strong></div>
		<div class="muted-info"><%= @project.location %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @project.fee %>円&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<% if user_signed_in? %><%= render 'project_favorites/favorite', project: @project %><% end %></div>
	</div>
</div>
<div class="project-info-content clearfix">
	<div class="project-info-main">
		<div class="project-info-title">工事内容について</div>
		<p class="english-info-title">ABOUT JOB</p>
		<div class="project-info-text"><%= simple_format(@project.project_content) %> </div>
		<div class="project-info-title">求めている人物像</div>
		<p class="english-info-title">IDEAL</p>
		<div class="project-info-text">
			<必須条件><br>
			<%= simple_format(@project.required_skill) %><br>
			<歓迎条件>
			<%= simple_format(@project.welcome_skill) %>
		</div>
		<div class="divider-top">
			<table class="table">
				<tbody>
					<tr>
						<td>報酬</td>
						<td><%= @project.fee %></td>
					</tr>
					<tr>
						<td>現場住所</td>
						<td><%= @project.location %><%= @project.detail_location %></td>
					</tr>
					<tr>
						<td>勤務時間</td>
						<td><%= @project.time %></td>
					</tr>
					<tr>
						<td>工期</td>
						<td><%= @project.first_term %>〜<%= @project.second_term %></td>
					</tr>
					<tr>
						<td>募集職種</td>
						<td><%= @project.genre %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="project-info-side">
		<% if user_signed_in? %>
			<% if @project.user.id == current_user.id %>
				<%= link_to edit_project_path(@project.id) do %>
					<div class="company-message">
						<p class="company-message-text">この情報を編集する</p>
					</div>
				<% end %>
			<% else %>
				<%= link_to rooms_path(id: @project.user.id),method: :post do %>
					<div class="company-message">
						<p class="company-message-text">メッセージを送る</p>
					</div>
				<% end %>
			<% end %>
			<div class="company-detail">
				<% if @project.user.id == current_user.id %>
					<%= link_to project_path(@project.id), method: :delete, data: {confirm: "この情報を削除してよろしいですか？"} do %>
						<div class="company-delete">
						<p class="company-message-text">この情報を削除する</p>
					</div>
					<% end %>
				<% else %>
					<%= link_to user_path(@project.user.id) do %>
						<P class="btn btn-detail">会社の詳細情報を見る</P>
					<% end %>
				<% end %>
			</div>
		<% else %>
				<%= link_to rooms_path(@project.user.id) do %>
					<div class="company-message">
						<p class="company-message-text">メッセージを送る</p>
					</div>
				<% end %>
				<div class="company-detail">
					<%= link_to user_path(@project.user.id) do %>
						<P class="btn btn-detail">会社の詳細情報を見る</P>
					<% end %>
				</div>
		<% end %>
		<div class="side-company">
			<div class="side-company-name">
				<%= @project.user.name %>
				<p><%= @project.user.residence %><%= @project.user.detail_residence %></p>
			</div>
			<table class="company-side-info">
				<tbody>
					<tr>
						<td>設立年</td>
						<td><%= @project.user.establishment %></td>
					</tr>
					<tr>
						<td>従業員数</td>
						<td><%= @project.user.employee %></td>
					</tr>
					<tr>
						<td>平均年齢</td>
						<td><%= @project.user.average_age %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="side-skill">
			<div class="side-company-skill"">対応工事</div>
			<% unless @project.user.skill == nil %>
				<% @user_skills.each do |skill| %>
					<li class="btn btn-side-skill"><%= skill %></li>
				<% end %>
			<% end %>
		</div>
	</div>
</div>