config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   password: 'users/passwords',
  #   registrations: 'users/registrations'
  # }
  devise_scope :user do
    post 'users', to: 'users/registrations#create'
  end
  root to: 'tops#index'
  get 'users/history'
  get 'users/favorite'
  get 'tops/show'
  devise_for :users
  get 'projects/search'
  get 'free_traders/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :rooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  resources :projects, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :project_favorites, only: [:create, :destroy]
  end

  resources :free_traders, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :trader_favorites, only: [:create, :destroy]
  end
end

app/models/free_trader.rb
class FreeTrader < ApplicationRecord

  validates :trader_title, presence: true
  validates :trader_genre, presence: true
  validates :area, presence: true
  validates :first_term, presence: true
  validates :second_term, presence: true



	belongs_to :user

	has_many :trader_favorites, dependent: :destroy

	enum trader_genre: {
		LGS:1,クロス:2,左官:3,ガラス:4,貼床:5,荷揚:6,雑工:7,電気:8,塗装:9,大工:10,シール:11,鳶:12,置床:13,防災:14,サイン:15,サッシ:16,建具:17,デザイン:18,設計:19,施工管理:20
	}

	def favorited_by?(user)
		trader_favorites.where(user_id: user.id).exists?
	end
end

app/controllers/free_traders_controller.rb
class FreeTradersController < ApplicationController
  def index
    @free_traders = FreeTrader.all.page(params[:page]).per(10)
    expired = FreeTrader.where("first_term < ?", Date.today)
    expired.each do |expired|
    expired.destroy
    end
  end

  def show
    @free_trader = FreeTrader.find(params[:id])
    unless @free_trader.user.skill == nil
      @user_skills = @free_trader.user.skill.split(", ")
    end
    unless @free_trader.area == nil
      @trader_areas = @free_trader.area.split(",")
    end
  end

  def edit
    @free_trader = FreeTrader.find(params[:id])
    if @free_trader.user_id != current_user.id
      redirect_to root_path
    end
  end

  def update
    free_trader = FreeTrader.find(params[:id])
    unless area_params[:area] == nil
      area = area_params[:area].join(",")
      free_trader.update(trader_title:free_trader_params[:trader_title], wanted_detail:free_trader_params[:wanted_detail], trader_genre:free_trader_params[:trader_genre],
                                   first_number_of_people:free_trader_params[:first_number_of_people], second_number_of_people:free_trader_params[:second_number_of_people],
                                   first_term:free_trader_params[:first_term], second_term:free_trader_params[:second_term], area:area)
      redirect_to free_trader_path(free_trader.id)
    else
      free_trader.update(free_trader_params)
      redirect_to free_trader_path(free_trader.id)
    end
  end

  def new
    @free_trader = FreeTrader.new
  end

  def create
    unless area_params[:area] == nil
      area = area_params[:area].join(",")
      @free_trader = FreeTrader.new(trader_title:free_trader_params[:trader_title], wanted_detail:free_trader_params[:wanted_detail], trader_genre:free_trader_params[:trader_genre],
                                   first_number_of_people:free_trader_params[:first_number_of_people], second_number_of_people:free_trader_params[:second_number_of_people],
                                   first_term:free_trader_params[:first_term], second_term:free_trader_params[:second_term], area:area)
      @free_trader.user_id = current_user.id
      if @free_trader.save
        redirect_to free_trader_path(@free_trader.id)
      else
        render 'new'
      end
    else
      @free_trader = FreeTrader.new(free_trader_params)
      @free_trader.user_id = current_user.id
      if @free_trader.save
        redirect_to free_trader_path(@free_trader.id)
      else
        render 'new'
      end
    end
  end

  def destroy
    free_trader = FreeTrader.find(params[:id])
    free_trader.destroy
    redirect_to user_path(current_user)
  end

  def search
    expired = FreeTrader.where("first_term < ?", Date.today)
    expired.each do |expired|
    expired.destroy
  end
    @free_traders = FreeTrader.where("trader_title like '%" + params[:search] +
                                     "%' and trader_genre like '%" + FreeTrader.trader_genres[params[:trader_genre]].to_s +
                                     "%' and area like '%" + params[:area] + "%'")
  end

  private
   def free_trader_params
      params.require(:free_trader).permit(:trader_title,:wanted_detail,:trader_genre,:first_number_of_people,:second_number_of_people,:first_term, :second_term)
  end
  def area_params
      params.require(:free_trader).permit(area:[])
  end
end

app/helpers/free_traders_helper.rb
module FreeTradersHelper
end

app/views/free_traders/index.html.erb
<div class="project-serch">
  <%= form_tag free_traders_search_path, method: :get do %>
    <div class= "search-area">
      <%= label_tag :キーワード %><br/>
      <%= text_field_tag :search, params[:search], class: "search_box" %>
    </div>
    <div class="search-area">
      <%= label_tag :職種 %><br/>
      <%= select_tag 'trader_genre', options_for_select(FreeTrader.trader_genres.keys), :include_blank => true, class: "genre_box" %>
    </div>
    <div class="search-area">
      <%= label_tag :対応エリア %><br/>
      <select name="area" id="area" class="location_box">
        <option value="">選択してください</option>
        <option value="北海道">北海道</option>
        <option value="青森">青森県</option>
        <option value="岩手">岩手県</option>
        <option value="宮城">宮城県</option>
        <option value="秋田">秋田県</option>
        <option value="山形">山形県</option>
        <option value="福島">福島県</option>
        <option value="茨城">茨城県</option>
        <option value="栃木">栃木県</option>
        <option value="群馬">群馬県</option>
        <option value="埼玉">埼玉県</option>
        <option value="千葉">千葉県</option>
        <option value="東京">東京都</option>
        <option value="神奈川">神奈川県</option>
        <option value="新潟">新潟県</option>
        <option value="富山">富山県</option>
        <option value="石川">石川県</option>
        <option value="福井">福井県</option>
        <option value="山梨">山梨県</option>
        <option value="長野">長野県</option>
        <option value="岐阜">岐阜県</option>
        <option value="静岡">静岡県</option>
        <option value="愛知">愛知県</option>
        <option value="三重">三重県</option>
        <option value="滋賀">滋賀県</option>
        <option value="京都">京都府</option>
        <option value="大阪">大阪府</option>
        <option value="兵庫">兵庫県</option>
        <option value="奈良">奈良県</option>
        <option value="和歌山">和歌山県</option>
        <option value="鳥取">鳥取県</option>
        <option value="島根">島根県</option>
        <option value="岡山">岡山県</option>
        <option value="広島">広島県</option>
        <option value="山口">山口県</option>
        <option value="徳島">徳島県</option>
        <option value="香川">香川県</option>
        <option value="愛媛">愛媛県</option>
        <option value="高知">高知県</option>
        <option value="福岡">福岡県</option>
        <option value="佐賀">佐賀県</option>
        <option value="長崎">長崎県</option>
        <option value="熊本">熊本県</option>
        <option value="大分">大分県</option>
        <option value="宮崎">宮崎県</option>
        <option value="鹿児島">鹿児島県</option>
        <option value="沖縄">沖縄県</option>
      </select>
    </div>
    <%= submit_tag "検索", class: "btn btn-search" %>
  <% end %>
</div>
<div class="project-content clearfix">
  <div class="project-main clearfix">
    <p>空き業者一覧</p>
    <% @free_traders.each do |trader| %>
      <div class="project-box">
        <div class="project-box-top clearfix">
          <div class="btn btn-title"><%= trader.trader_genre %></div>
            <% a = trader.first_term %>
            <% b = (a - Date.today).to_i %>
            <% if b <= 10 %>
            <div class="btn btn-deadline"> あと<%= b %>日</div>
            <% else %>
            <div class="btn btn-title"> あと<%= b %>日</div>
            <% end %>
            <% if user_signed_in? %>
              <div class="project-box-favorite"><%= render 'trader_favorites/favorite', trader: trader %></div>
            <% end %>
        </div>
        <%= link_to free_trader_path(trader.id) do %>
          <div class="project-box-text"><%= trader.trader_title %></div>
          <div class="box-info clearfix">
            <div class="box-info-left">
              <div class="project-box-name"><%= trader.user.name %></div>
              <div class="project-box-info"><%= trader.user.residence %></div>
            </div>
            <div class="trader-info-right">
              <div class="project-box-image"><%= attachment_image_tag trader.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= paginate @free_traders %>
  </div>
  <div class="project-side">
    <div class="side-search-title">おすすめ検索ワード</div>
      <p>対応エリア</p>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=東京"><li class="btn btn-default">東京</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=神奈川"><li class="btn btn-default">神奈川</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=大阪"><li class="btn btn-default">大阪</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=埼玉"><li class="btn btn-default">埼玉</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=福岡"><li class="btn btn-default">福岡</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=北海道"><li class="btn btn-default">北海道</li></a>
      <p>職種</p>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=大工&area=&"><li class="btn btn-default">大工</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=左官&area=&"><li class="btn btn-default">左官</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=塗装&area=&"><li class="btn btn-default">塗装</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=施工管理&area=&"><li class="btn btn-default">施工管理</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=設計&area=&"><li class="btn btn-default">設計</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=デザイン&area=&"><li class="btn btn-default">デザイナー</li></a>
    </div>
</div>

app/views/free_traders/search.html.erb
<div class="project-serch">
    <%= form_tag free_traders_search_path, method: :get do %>
    <div class= "search-area">
      <%= label_tag :キーワード %><br/>
      <%= text_field_tag :search, params[:search], class: "search_box" %>
    </div>
    <div class="search-area">
      <%= label_tag :職種 %><br/>
      <%= select_tag 'trader_genre', options_for_select(FreeTrader.trader_genres.keys), :include_blank => true, class: "genre_box" %>
    </div>
    <div class="search-area">
      <%= label_tag :対応エリア %><br/>
      <select name="area" id="area" class="location_box">
         <option value="">選択してください</option>
         <option value="北海道">北海道</option>
         <option value="青森">青森県</option>
         <option value="岩手">岩手県</option>
         <option value="宮城">宮城県</option>
         <option value="秋田">秋田県</option>
         <option value="山形">山形県</option>
         <option value="福島">福島県</option>
         <option value="茨城">茨城県</option>
         <option value="栃木">栃木県</option>
         <option value="群馬">群馬県</option>
         <option value="埼玉">埼玉県</option>
         <option value="千葉">千葉県</option>
         <option value="東京">東京都</option>
         <option value="神奈川">神奈川県</option>
         <option value="新潟">新潟県</option>
         <option value="富山">富山県</option>
         <option value="石川">石川県</option>
         <option value="福井">福井県</option>
         <option value="山梨">山梨県</option>
         <option value="長野">長野県</option>
         <option value="岐阜">岐阜県</option>
         <option value="静岡">静岡県</option>
         <option value="愛知">愛知県</option>
         <option value="三重">三重県</option>
         <option value="滋賀">滋賀県</option>
         <option value="京都">京都府</option>
         <option value="大阪">大阪府</option>
         <option value="兵庫">兵庫県</option>
         <option value="奈良">奈良県</option>
         <option value="和歌山">和歌山県</option>
         <option value="鳥取">鳥取県</option>
         <option value="島根">島根県</option>
         <option value="岡山">岡山県</option>
         <option value="広島">広島県</option>
         <option value="山口">山口県</option>
         <option value="徳島">徳島県</option>
         <option value="香川">香川県</option>
         <option value="愛媛">愛媛県</option>
         <option value="高知">高知県</option>
         <option value="福岡">福岡県</option>
         <option value="佐賀">佐賀県</option>
         <option value="長崎">長崎県</option>
         <option value="熊本">熊本県</option>
         <option value="大分">大分県</option>
         <option value="宮崎">宮崎県</option>
         <option value="鹿児島">鹿児島県</option>
         <option value="沖縄">沖縄県</option>
      </select>
    </div>
    <%= submit_tag "検索", class: "btn btn-search" %>
  <% end %>
</div>
<div class="project-content clearfix">
  <div class="project-main clearfix">
    <% if @free_traders.present? %>
      <p>空き業者検索結果</p>
     	<% @free_traders.each do |trader| %>
        <%= link_to free_trader_path(trader.id) do %>
          <div class="project-box">
            <div class="btn btn-title"><%= trader.trader_genre %></div>
            <% a = trader.first_term %>
            <% b = (a - Date.today).to_i %>
            <% if b <= 10 %>
              <div class="btn btn-deadline"> あと<%= b %>日</div>
            <% else %>
              <div class="btn btn-title"> あと<%= b %>日</div>
            <% end %>
            <div class="project-box-text"><%= trader.trader_title %></div>
            <div class="box-info clearfix">
              <div class="box-info-left">
                <div class="project-box-name"><%= trader.user.name %></div>
                <div class="project-box-info"><%= trader.user.residence %></div>
              </div>
              <div class="trader-info-right">
     	          <div class="project-box-image"><%= attachment_image_tag trader.user, :profile_image, :fill, 120, 120, format: 'jpeg',class: "img-circle", fallback: "user1.png", :size => "56x56" %></div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="search-nil">
        <div class="search-nill-text"><% if params[:search].present? %>「<%= params[:search] %>」</br><% end %>
                                      <% if params[:trader_genre].present? %>「<%= params[:trader_genre] %>」<% end %>
                                      <% if params[:area].present? %>「<%= params[:area] %>」<% end %><br/>該当結果なし
        </div>
      </div>
    <% end %>
  </div>
  <div class="project-side">
    <div class="side-search-title">おすすめ検索ワード</div>
    <p>対応エリア</p>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=東京"><li class="btn btn-default">東京</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=神奈川"><li class="btn btn-default">神奈川</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=大阪"><li class="btn btn-default">大阪</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=埼玉"><li class="btn btn-default">埼玉</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=福岡"><li class="btn btn-default">福岡</li></a>
      <a href="/free_traders/search?utf8=✓&search=&trader_genre=&area=北海道"><li class="btn btn-default">北海道</li></a>
      <p>職種</p>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=大工&area=&"><li class="btn btn-default">大工</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=左官&area=&"><li class="btn btn-default">左官</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=塗装&area=&"><li class="btn btn-default">塗装</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=施工管理&area=&"><li class="btn btn-default">施工管理</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=設計&area=&"><li class="btn btn-default">設計</li></a>
      <a href= "/free_traders/search?utf8=✓&search=&trader_genre=デザイン&area=&"><li class="btn btn-default">デザイナー</li></a>
  </div>
</div>

app/views/free_traders/show.html.erb
<div class="project-info">
    <div class="project-info-top">
        <div class="client-image">
            <%= attachment_image_tag @free_trader.user, :profile_image, :fill, 120, 120, format: 'jpeg', fallback: "user1.png", :size => "100x100" %>
        </div>
        <div class="btn btn-genre"><%= @free_trader.trader_genre %></div>
        <% a = @free_trader.first_term %>
        <% b = (a - Date.today).to_i %>
        <% if b <= 10 %>
            <div class="btn btn-deadline-show"> あと<%= b %>日</div>
        <% else %>
            <div class="btn btn-genre"> あと<%= b %>日</div>
        <% end %>
        <div class="project-title"><strong><%= @free_trader.trader_title %></strong></div>
        <div class="muted-info"><%= @free_trader.user.residence %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <% if user_signed_in? %><%= render 'trader_favorites/favorite', trader: @free_trader %><% end %></div>
    </div>
</div>
<div class="project-info-content clearfix">
    <div class="project-info-main">
        <div class="project-info-title">詳細</div>
        <p class="english-info-title">Detail</p>
        <div class="project-info-text"><%= simple_format(@free_trader.wanted_detail) %> </div>
        <div class="divider-top">
            <table class="table">
                <tbody>
                    <tr>
                        <td>会社住所</td>
                        <td><%= @free_trader.user.residence %><%= @free_trader.user.detail_residence %></td>
                    </tr>
                    <tr>
                        <td>空き人数</td>
                        <td><%= @free_trader.first_number_of_people %>人〜<%= @free_trader.second_number_of_people %>人</td>
                    </tr>
                    <tr>
                        <td>対応期間</td>
                        <td><%= @free_trader.first_term %>〜<%= @free_trader.second_term %></td>
                    </tr>
                    <tr>
                        <td>職種</td>
                        <td><%= @free_trader.trader_genre %></td>
                    </tr>
                    <tr>
                        <td>対応可能エリア</td>
                        <td>
                            <% unless @trader_areas == nil %>
                                <% @trader_areas.each do |area| %>
                                    <li class="btn btn-area"><%= area %></li>
                                <% end %>
                            <% end %>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="project-info-side">
        <% if user_signed_in? %>
            <% if @free_trader.user_id == current_user.id %>
                <%= link_to edit_free_trader_path(@free_trader.id) do %>
                    <div class="company-message">
                        <p class="company-message-text">情報を編集する</p>
                    </div>
                <% end %>
            <% else %>
                <%= link_to rooms_path(id: @free_trader.user.id),method: :post do %>
                    <div class="company-message">
                        <p class="company-message-text">メッセージを送る</p>
                    </div>
                <% end %>
            <% end %>
            <div class="company-detail">
                <% if @free_trader.user_id == current_user.id %>
                    <%= link_to free_trader_path(@free_trader.id), method: :delete, data: {confirm: "この情報を削除してよろしいですか？"} do %>
                        <div class="company-delete">
                            <p class="company-message-text">この情報を削除する</p>
                        </div>
                    <% end %>
                <% else %>
                    <%= link_to user_path(@free_trader.user.id) do %>
                        <P class="btn btn-detail">会社の詳細情報を見る</P>
                    <% end %>
                <% end %>
            </div>
        <% else %>
                <%= link_to rooms_path(@free_trader.user.id) do %>
                    <div class="company-message">
                        <p class="company-message-text">メッセージを送る</p>
                    </div>
                <% end %>
                <div class="company-detail">
                    <%= link_to user_path(@free_trader.user.id) do %>
                        <P class="btn btn-detail">会社の詳細情報を見る</P>
                    <% end %>
                </div>
        <% end %>
        <div class="side-company">
            <div class="side-company-name">
                <%= @free_trader.user.name %>
                <p><%= @free_trader.user.residence %><%= @free_trader.user.detail_residence %></p>
            </div>
            <table class="company-side-info">
              <tbody>
                <tr>
                  <td>設立年</td>
                  <td><%= @free_trader.user.establishment %></td>
                </tr>
                <tr>
                  <td>従業員数</td>
                  <td><%= @free_trader.user.employee %></td>
                </tr>
                <tr>
                  <td>平均年齢</td>
                  <td><%= @free_trader.user.average_age %></td>
                </tr>
              </tbody>
            </table>
        </div>
        <div class="side-skill">
            <div class="side-company-skill"">対応工事</div>
            <% unless @user_skills == nil %>
                <% @user_skills.each do |skill| %>
                  <li class="btn btn-side-skill"><%= skill %></li>
                <% end %>
            <% end %>
        </div>
    </div>
</div>