config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   password: 'users/passwords',
  #   registrations: 'users/registrations'
  # }
  devise_scope :user do
    post 'users', to: 'users/registrations#create'
  end
  root to: 'tops#index'
  get 'users/history'
  get 'users/favorite'
  get 'tops/show'
  devise_for :users
  get 'projects/search'
  get 'free_traders/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :rooms, only: [:index, :show, :create, :destroy] do
    resources :messages, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]

  resources :projects, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :project_favorites, only: [:create, :destroy]
  end

  resources :free_traders, only: [:index,:show,:new,:create,:edit,:update,:destroy] do
    resource :trader_favorites, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>

  <body>
      <% if user_signed_in? %>
        <header class= "navbar navbar-main">
                <nav class= "nav navbar-nav navbar-left">
                  <span class="header-title">IC.inc</span>
                    <% if notice %>
                      <span id="notice"><%= notice %></span>
                    <% end %>
                </nav>
                <nav class="nav navbar-nav navbar-right">
                  <ul id="menu">
                    <li>
                      <%=link_to " Home", root_path %>
                    </li>
                    <li>投稿
                      <ul class="child">
                        <li><%= link_to "案件情報投稿", new_project_path %></li>
                        <li><%= link_to "空き情報投稿", new_free_trader_path %></li>
                      </ul>
                    </li>
                    <li>案件を探す
                      <ul class="child">
                        <li><%=link_to "案件情報", projects_path %></li>
                        <li><%= link_to "下請け情報", free_traders_path %></li>
                      </ul>
                    </li>
                    <li class="aaa">プロフィール
                        <% unread = Unread.where("user_id = ? and count > 0", current_user.id) %>
                        <% count = 0 %>
                        <% unread.each do |unread| %>
                          <% count += unread.count %>
                        <% end %>
                        <% if unread.count > 0 %>
                          <span class="header-top-unread"></span>
                        <% end %>
                      <ul class="child">
                        <li><%= link_to "My page", user_path(current_user.id) %></li>
                        <li><%= link_to "お気に入り", users_favorite_path %></li>
                        <li><%= link_to "投稿履歴", users_history_path %></li>
                        <li><%= link_to rooms_path do %>
                          メッセージ
                        <% if unread.count > 0 %>
                          <span class="header-unread"><%= "#{count}" %></span>
                        <% end %>
                        <% end %>
                        </li>
                        <li><%= link_to " Logout", destroy_user_session_path, method: :delete %></li>
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </header>
      <% else %>
        <header class= "navbar navbar-main">
                <nav class= "nav navbar-nav navbar-left">
                  <span class="header-title">IC.inc</span>
                </nav>
                <nav class="nav navbar-nav navbar-right">
                  <ul id="menu">
                    <li>
                      <%=link_to " Home", root_path %>
                    </li>
                    <li>案件を探す
                      <ul class="child">
                        <li><%=link_to "案件情報", projects_path %></li>
                        <li><%= link_to "下請け情報", free_traders_path %></li>
                      </ul>
                    </li>
                    <li>アカウント登録
                      <ul class="child">
                        <li><%= link_to "ログイン", tops_show_path %></li>
                      </ul>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </header>
      <% end %>
    <%= yield %>
  </body>
</html>